"""add inspection severity fields

Revision ID: 07b2f6305e2c
Revises: f466daec3eb1
Create Date: 2026-08-16 17:31:25.908770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b2f6305e2c'
down_revision: Union[str, Sequence[str], None] = 'f466daec3eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('inspections', sa.Column('severity_score', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('severity_factors', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'severity_factors')
    op.drop_column('inspections', 'severity_score')
    op.drop_column('inspections', 'severity')
    # ### end Alembic commands ###
